# -*- coding: utf-8 -*-
"""fix_notebook

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LPXGd8VmOgto7Y79ms8MLr_vZrO87lwi
"""

import json

notebook_file = 'Model_Training(fn).ipynb'

with open(notebook_file, 'r') as f:
    notebook = json.load(f)

if 'metadata' in notebook and 'widgets' in notebook['metadata']:
    del notebook['metadata']['widgets']
    print("Removed widgets metadata - outputs preserved!")
else:
    print("No widgets metadata found")

with open(notebook_file, 'w') as f:
    json.dump(notebook, f, indent=2)

print(f"Fixed {notebook_file}!")